### ISSUE TITLE
Add a new broker listener allowing docker to docker communication

### ISSUE THREAD

**Issue by lurajon** [navikt/navkafka-docker-compose#5]
It would be beneficial to allow another docker container to connect to navkafka through the host.docker.internal name.

```yaml
environment:
...
    - "KAFKA_LISTENERS=DOCKERHOST://0.0.0.0:29092,SASLPLAINTEXT://0.0.0.0:9092,SASLINTERNAL://kafka:9093"
    - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=DOCKERHOST:SASL_PLAINTEXT,SASLPLAINTEXT:SASL_PLAINTEXT,SASLINTERNAL:SASL_PLAINTEXT"
    - "KAFKA_ADVERTISED_LISTENERS=DOCKERHOST://host.docker.internal:29092,SASLPLAINTEXT://localhost:9092,SASLINTERNAL://kafka:9093"
    - "KAFKA_PROTOCOL_NAME=DOCKERHOST,SASLPLAINTEXT,SASLINTERNAL"
    - "KAFKA_LISTENER_NAME_DOCKERHOST_PLAIN_SASL_SERVER_CALLBACK_HANDLER_CLASS=no.nav.common.security.authentication.SimpleLDAPAuthentication"
...
    ports:
    - "9092:9092"
    - "29092:29092"
```
